version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rolwebapp-db
    environment:
      POSTGRES_DB: rolwebapp
      POSTGRES_USER: roluser
      POSTGRES_PASSWORD: rolpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rol-net

  app:
    build:
      context: .
    container_name: rolwebapp-app
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/rolwebapp
      SPRING_DATASOURCE_USERNAME: roluser
      SPRING_DATASOURCE_PASSWORD: rolpass
    networks:
      - rol-net

  frontend:
    build:
      context: ../frontend
    container_name: rolwebapp-frontend
    ports:
      - "3000:4173"
    networks:
      - rol-net

volumes:
  pgdata:

networks:
  rol-net:
    driver: bridge